version: '1'

services:
  discovery-ms:
    build:
      context: ./
      dockerfile: discovery-ms/Dockerfile
    ports:
      - "8761:8761"
    container_name: discovery-ms

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

  employee-ms:
    build:
      context: ./
      dockerfile: employee-ms/Dockerfile
    ports:
      - "8081:8081"
    container_name: employee-ms
    links:
      - mongo-db
      - rabbitmq

  notification-ms:
    build:
      context: ./
      dockerfile: notification-ms/Dockerfile
    ports:
      - "8082:8082"
    container_name: notification-ms
    links:
      - rabbitmq